### ISSUE TITLE
ListView Command Set: event.selectedRows returns wrong ID, when there is a pinned document in the library

### ISSUE THREAD

**Issue by oliverlp** [pnp/sp-dev-fx-extensions#267]
- [ ] Question
- [x] Bug
- [ ] Enhancement
Expected or Desired Behavior
In a library with a pinned document, when I selected a document from a view, the Listview Command Set will return the ID of the selected document, and not the ID of the pinned document.

SPFx version 1.4 and 1.8

Observed Behavior
event.selectedRows[0].getValueByName('ID') returns the ID of the pinned document, not the selected row in the library

Steps to Reproduce
Create a listview command set and apply it to a library.
Add 4. documents, and pin one of them.
Select one of the others and click on the command. The event will return a wrong ID.

**Comment by oliverlp** [comment]
Hi @andrewconnell ,

Do you this this is related to #4769 [ListViewCommand: event.selectedRows not updating] and #4772 ["ListView CommandSet - onExecute parameters has wrong selectedRows (in a Doc Library) ] ?

Thanks in advance. 
Oliver

**Comment by oliverlp** [comment]
This is solved now.

**Comment by teresahoes** [comment]
i am still seeing this issue w/ 1.51 version of spfx.  what is the resolution? do i have to upgrade to a newer version of spfx or was it something not rolled out to our tenant?

**Comment by johannes-z** [comment]
@oliverlp Still an issue using SPFx 1.11, targetting SPO.

**Comment by hugoabernier** [comment]
@johannes-z @teresahoes the `selectedRows` prop is intended to return a reference to a list item rows, not an HTML table row. Hence, it works as expected.

For example, you can get the relativeUrl of a selected file in a document library by calling:
```typescript
relativeUrl = event.selectedRows[0].getValueByName('FileRef');
```

While there is no matching HTML attribute.

This issues list is intended for issues related to sample extensions in this repository. Please refer to https://github.com/SharePoint/sp-dev-docs for general questions about SPFx web parts and extension development.

I hope this helps?

**Comment by johannes-z** [comment]
@hugoabernier That's not the issue.

If you pin a document in a library, the `event.selectedRows` is an array of all the pinned documents (I think), rather than the actually selected ones. At least in my case, `event.selectedRows` was always an array of references to the pinned documents, rather than the selected rows in the ListViewWebPart. I've opened a issue here: https://github.com/SharePoint/sp-dev-docs/issues/6077

**Comment by tony-philipose** [comment]
I have the same issue : `event.selectedRows` is an array of all the pinned documents rather than the actually selected ones.

**Comment by oliverlp** [comment]
The bug is back in my tenant. This is really a problem. The users execute a command against the wrong document.

**Comment by hugoabernier** [comment]
This issue list is intended for issues related to extension samples in this repository. It isn't monitored by support staff. 

You may want to open an issue with https://github.com/SharePoint/sp-dev-docs/issues instead
